from cohere.responses.classify import Example

examples = [
      Example("Today was an extraordinary day! Received news of a promotion at work, and the joy is overwhelming. Celebrated with colleagues and shared the happiness with friends. Grateful for the recognition and the support of loved ones. Spent the evening surrounded by laughter and good company. Feeling on top of the world!", "Very Happy"),
      Example("Faced a setback at work today. The project didn't go as planned, and I'm feeling disappointed and frustrated. Spent the evening reflecting on what went wrong and thinking about how to bounce back. It's a tough pill to swallow, but I'm determined to learn from this experience and come back stronger. Tomorrow is a new day.", "Sad"),
      Example("A typical Wednesday. Worked through the usual tasks and attended a few meetings. Nothing extraordinary happened, but everything went smoothly. Took a short walk during lunch to clear my mind. The weather was pleasant. A calm and uneventful day overall.", "Neutral"),
      Example("Had a lovely evening with friends. We went out for dinner and shared stories and laughter. It's amazing how good company can lift your spirits. Grateful for the friendships that bring so much joy into my life. Looking forward to more moments like these.", "Happy"),
      Example("Received news of a loss in the family today. The grief is overwhelming, and my heart aches. Spent the day reminiscing about the beautiful moments shared with the departed soul. It's a challenging time, and emotions are raw. Grateful for the support of family and friends during this difficult period.", "Very Sad"),
      Example("Received news of a loss in the family today. The grief is overwhelming, and my heart aches. Spent the day reminiscing about the beautiful moments shared with the departed soul. It's a challenging time, and emotions are raw. Grateful for the support of family and friends during this difficult period.", "Very Sad"),
      Example("Attended a virtual art class today. Painting has always been a therapeutic outlet for me. Created a vibrant masterpiece and felt a sense of accomplishment. Art has a way of bringing joy and peace. Grateful for the creative moments that add color to life.", "Happy"),
      Example("Sunday at home. Did some household chores and relaxed with a good book. The day passed by in a quiet and laid-back manner. Sometimes, embracing simplicity and tranquility is a gift in itself.", "Neutral"),
      Example("Spent the day exploring a new city. Every corner held surprises, and the adventure filled my heart with joy. Discovered charming cafes, met friendly locals, and captured breathtaking views. Gratitude for the beauty and diversity in the world.", "Very Happy"),
      Example("Received news of a dear friend moving away. The realization of the distance hits hard, and a sense of loss lingers. Said heartfelt goodbyes, cherishing the memories. Change is inevitable, but it doesn't make farewells any easier.", "Sad"),
      Example("Completed a challenging workout today. The endorphin rush is real, and the sense of accomplishment is empowering. Physical activity truly has a positive impact on mood and well-being. Feeling energized and ready to conquer the day.", "Happy"),
      Example("Sunday at home. Did some household chores and relaxed with a good book. The day passed by in a quiet and laid-back manner. Sometimes, embracing simplicity and tranquility is a gift in itself.", "Neutral"),
      Example("Spent the day exploring a new city. Every corner held surprises, and the adventure filled my heart with joy. Discovered charming cafes, met friendly locals, and captured breathtaking views. Gratitude for the beauty and diversity in the world.", "Very Happy"),
      Example("Received news of a dear friend moving away. The realization of the distance hits hard, and a sense of loss lingers. Said heartfelt goodbyes, cherishing the memories. Change is inevitable, but it doesn't make farewells any easier.", "Sad"),
      Example("Completed a challenging workout today. The endorphin rush is real, and the sense of accomplishment is empowering. Physical activity truly has a positive impact on mood and well-being. Feeling energized and ready to conquer the day.", "Happy"),
  ]
my_summaries = {
        "summaries" : [
            'I am so surprised and delighted by the surprise birthday party my family and friends prepared for me. The decorations, greetings, hugs, and shared memories made the day so special and unforgettable. I am so grateful for these precious people in my life.',
            'I reflect on my graduation day, a mix of emotions from joy to nostalgia. I felt proud and accomplished, surrounded by classmates and family cheering me on. I cherish this milestone, marking the end of one chapter and the start of another closer to my dreams.',
            'I met my soulmate at a coffee shop. Our conversation was easy, and we felt a strong connection. That meeting changed my life as I knew it, and I found true love.',
            'Today marked the achievement of a lifelong dream. I received an offer for my dream job! After years of dedication, hard work, and countless setbacks, the call finally came. The moment I heard the words "We\'d like to offer you the position," my heart leapt with joy. I was overwhelmed with emotions; tears of happiness, relief, and excitement for what lies ahead. This opportunity is not just a job, but a chance to make a significant impact in a field I\'m passionate about. Today, I celebrate not just an offer, but a dream turning into reality.',
            'Embarking on the adventure of a lifetime was today\'s highlight. I always dreamed of traveling the world, and finally, I took the leap. Standing atop a mountain, overlooking a vista that stretched infinitely, I felt an unparalleled sense of freedom and accomplishment. The journey here was filled with challenges, yet each step was worth the breathtaking view. The beauty of the world, so vast and majestic, reminded me of the endless possibilities that life offers. Today, I lived my dream of adventure, a memory that fuels my soul \'s wanderlust.'
        ]
    }
